"""Add User model and owner_id to Book

Revision ID: 5b1a31b4c2b8
Revises: 782be81b9acd
Create Date: 2025-10-27 14:08:28.568141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1a31b4c2b8'
down_revision: Union[str, Sequence[str], None] = '782be81b9acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_books_barcode'), 'books', ['barcode'], unique=False)
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
    
    # Créer un utilisateur admin par défaut si la table users est vide
    op.execute("""
        INSERT OR IGNORE INTO users (email, username, hashed_password, is_active, created_at)
        VALUES ('admin@bibliotheque.local', 'admin', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdU5tTqLULjVJh2', 1, datetime('now'))
    """)
    
    # Assigner tous les livres existants au premier utilisateur
    op.execute("UPDATE books SET owner_id = 1 WHERE owner_id IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_barcode'), table_name='books')
    op.drop_column('books', 'owner_id')
    # ### end Alembic commands ###
