"""add_user_loan_requests_and_contact_user_link

Revision ID: 742303eb0e10
Revises: d3e4f5a6b7c8
Create Date: 2026-02-18 12:24:58.152263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742303eb0e10'
down_revision: Union[str, Sequence[str], None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'owner_id', name='uq_borrower_name_owner')
    )
    op.create_index(op.f('ix_borrowers_name'), 'borrowers', ['name'], unique=False)
    op.create_index(op.f('ix_borrowers_owner_id'), 'borrowers', ['owner_id'], unique=False)
    op.create_table('user_loan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('response_message', sa.String(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_loan_requests_book_id'), 'user_loan_requests', ['book_id'], unique=False)
    op.create_index(op.f('ix_user_loan_requests_lender_id'), 'user_loan_requests', ['lender_id'], unique=False)
    op.create_index(op.f('ix_user_loan_requests_requester_id'), 'user_loan_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_user_loan_requests_status'), 'user_loan_requests', ['status'], unique=False)
    op.add_column('books', sa.Column('is_lendable', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('contacts', sa.Column('linked_user_id', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('library_shared', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'contacts', 'users', ['linked_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'library_shared')
    op.drop_column('contacts', 'linked_user_id')
    op.drop_column('books', 'is_lendable')
    op.drop_index(op.f('ix_user_loan_requests_status'), table_name='user_loan_requests')
    op.drop_index(op.f('ix_user_loan_requests_requester_id'), table_name='user_loan_requests')
    op.drop_index(op.f('ix_user_loan_requests_lender_id'), table_name='user_loan_requests')
    op.drop_index(op.f('ix_user_loan_requests_book_id'), table_name='user_loan_requests')
    op.drop_table('user_loan_requests')
    op.drop_index(op.f('ix_borrowers_owner_id'), table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_name'), table_name='borrowers')
    op.drop_table('borrowers')
    # ### end Alembic commands ###
